name: Generate ASCII ART
on: push
jobs:
    generate_art:
        runs-on: ubuntu-latest
        steps:
        - name: download repo
          uses: actions/checkout@v4
        - name: install cowsay utility
          run: sudo apt-get install cowsay -y
        - name: generate sheep ASCII
          run: cowsay -f sheep "soot 2l5aroof bynb7, said by the sheep :)" >> sheep.txt
        - name: validate content
          run: grep -i "sheep" sheep.txt
        - name: show file content 
          run: cat sheep.txt
        - name: list files
          run: ls -ltar